rmcs_localization:
  ros__parameters:
    map_path: "/root/红方原点合并补偿.pcd"

    frames:
      world: "world"
      odom: "odom"

    subscription:
      pointcloud: "/cloud_registered_undistort"

    registration:
      initial_map_radius: 25.0
      coarse_iterations: 50
      precise_iterations: 500
      distance_threshold: 5.0
      threads: 8
      scan_angle: 15
      score_threshold: 0.01
      voxel_grid:
        lx: 0.2
        ly: 0.2
        lz: 0.2
      outlier_removal:
        mean_k: 50
        stddev_mul_thresh: 0.5

    initial_world_to_odom:
      red:
        t: [0.0, 0.0, 0.0]
        q: [1.0, 0.0, 0.0, 0.0]
      blue:
        t: [20.0, 0.0, 0.0]
        q: [0.0, 0.0, 0.0, 1.0]
