rmcs_localization:
  ros__parameters:
    map_path: "/path/to/map.pcd"

    frames:
      world: "world"
      odom: "odom"
      base: "base_link"

    subscription:
      pointcloud: "/cloud_registered"

    publish:
      robot_pose: "/rmcs_localization/pose"
      tf: true

    service:
      relocalize: "/rmcs_localization/relocalize"

    history:
      enable: true
      duration_sec: 10.0
      sample_period_sec: 0.05

    registration:
      receive_size: 2500
      initial_map_radius: 25.0
      coarse_iterations: 50
      precise_iterations: 500
      distance_threshold: 5.0
      threads: 8
      scan_angle: 15
      score_threshold: 0.01
      voxel_grid:
        lx: 0.2
        ly: 0.2
        lz: 0.2
      outlier_removal:
        mean_k: 50
        stddev_mul_thresh: 0.5

    segmentation:
      distance_threshold: 0.3
      ground_max_height: 0.3
      limit_distance: 50.0
      limit_max_height: 10.0

    default_pose:
      translation:
        x: 0.0
        y: 0.0
        z: 0.0
      orientation:
        w: 1.0
        x: 0.0
        y: 0.0
        z: 0.0
